# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: TODO
email: anders@brujordet.no
description: > # this means to ignore newlines until "baseurl:"
  I'm thinking this should be some great content. Very ground breaking.
  Very. Mostly not though. Maybe some bash. And automation stuff.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://brujoand.github.io" # the base hostname & protocol for your site
twitter_username: brujoand
github_username: brujoand

# Build settings
markdown: kramdown

theme: jekyll-theme-minimal